enable-bstats: true

update-check: true

# MySQL Database
database:
  enabled: false
  host: localhost
  database: db
  user: user
  pass: pass
  port: 3306
  ssl: true
  verify-certificate: true
  pool-size: 10
  max-lifetime: 1800